apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DB_USER: {{ .Values.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc }}
  DB_NAME: {{ .Values.DB_NAME | b64enc }}
  REFRESH_TOKEN: {{ .Values.REFRESH_TOKEN | b64enc }}
  ACCESS_TOKEN: {{ .Values.ACCESS_TOKEN | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}
  ADMIN_EMAIL: {{ .Values.ADMIN_EMAIL | b64enc }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD | b64enc }}
